# Generated by Django 4.2.7 on 2025-09-29 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_recognition_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facerecognitionsettings',
            name='confidence_threshold',
            field=models.FloatField(default=0.6, help_text='Umbral de confianza para considerar una coincidencia válida (menor valor = más estricto)'),
        ),
    ]
