# Generated by Django 4.2.7 on 2025-10-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_recognition_app', '0002_alter_facerecognitionsettings_confidence_threshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facerecognitionsettings',
            name='confidence_threshold',
            field=models.FloatField(default=0.55, help_text='Umbral de confianza para considerar una coincidencia válida (menor valor = más estricto)'),
        ),
    ]
