# Generated by Django 4.2.7 on 2025-09-18 01:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0004_attendancesession_permisividad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ficha',
            name='instructor',
        ),
        migrations.AddField(
            model_name='ficha',
            name='instructors',
            field=models.ManyToManyField(limit_choices_to={'role': 'instructor'}, related_name='fichas', to=settings.AUTH_USER_MODEL),
        ),
    ]
