# Generated by Django 4.2.7 on 2025-09-18 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_remove_ficha_instructor_ficha_instructors'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='jornada',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
