# Generated by Django 4.2.7 on 2025-09-29 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_ficha_jornada'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ficha',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
